# Used by docker-compose.yml
FROM hexpm/elixir:1.12.0-erlang-24.0.1-debian-bullseye-20210902-slim

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends build-essential dialog apt-utils gpg-agent \
    apt-transport-https software-properties-common git curl postgresql-client inotify-tools && \
    mix local.hex --force && \
    mix archive.install hex phx_new 1.6.7 --force && \
    mix local.rebar --force && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
WORKDIR /app
COPY . .
EXPOSE 4000
CMD /bin/sh -c "while sleep 1000; do :; done"